@startuml as is c4 container

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(user, "User")
System_Boundary(movie_app, "Movie app") {
    Container(web_app, "Main service", "Go")
    ContainerDb(pg, "Database", "PostgreSQL")
    SystemQueue(rabbitmq, "RabbitMQ")
}
System(online_movie, "Online movie")
System(s3, "S3")
System(payment_system, "Payment system")

Rel(user, web_app, "Uses", "HTTPS")
Rel(web_app, s3, "")
Rel(web_app, pg, "")
Rel(web_app, online_movie,"")
Rel(web_app, payment_system,"")
BiRel(web_app, rabbitmq,"")
@enduml